name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Npm_security_Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo  
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - name: Check npm Security
      run: npm run npm-security-test

  Build_and_Integration_Tests:
    runs-on: ubuntu-latest

    needs: Npm_security_Test
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Run Frontend
      run: npm run start-fe &
    - name: Wait Frontend to be Ready
      run: sleep 10
    - name: Run Backend
      run: npm run start-be &
    - name: Wait Backend to be Ready
      run: sleep 30
    - name: Integration Tests
      run: npm run test:ui